spring:
  application:
    name: hyodoring
  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?createDatabaseIfNotExist=true
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    hikari:
      pool-name: HikariCP
      minimum-idle: 5
      maximum-pool-size: 20
      max-lifetime: 1800000
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        jdbc:
          time_zone: UTC
  cloud:
    openfeign:
      client:
        config:
          default:
            connectTimeout: 5000
            readTimeout: 5000
            loggerLevel: full

  logging:
    level:
      root: WARN

cloud:
  aws:
    credentials:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}
    s3:
      bucket: hyodoring

springdoc:
  dev: ${DEV_SERVER_URL}

jwt:
  prefix: Bearer
  secret: ${JWT_SECRET_KEY}
  access-token:
    expiration-ms: 7200000 # 2h
  refresh-token:
    expiration-ms: 2592000000 # 30d

feign:
  client:
    kakao:
      url: ${KAKAO_BASE_URL}
