spring:
  application:
    name: hyodoring
  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?createDatabaseIfNotExist=true
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    hikari:
      pool-name: HikariCP
      minimum-idle: 5
      maximum-pool-size: 20
      max-lifetime: 1800000
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        jdbc:
          time_zone: UTC
  cloud:
    openfeign:
      client:
        config:
          default:
            connectTimeout: 5000
            readTimeout: 5000
            loggerLevel: full

  logging:
    level:
      root: WARN

springdoc:
  dev: ${DEV_SERVER_URL}

feign:
  client:
    kakao:
      url: ${KAKAO_BASE_URL}
